apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers-poc
spec:
  selector:
      matchLabels:
        app: ers-poc
  replicas: 1
  template:
      metadata:
        labels:
            app: ers-poc
      spec:
        containers:
        - name: ers-poc
          image: ersacr.azurecr.io/poc:v1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
